### PR TITLE
Added parity pmr types with enums

### PR DESCRIPTION
**Pull request by leovujanic**
Added "enums in index.js and full types (interfaces and enums).

The usage for this version would be like this:
```typescript
import * as PMR from "parity-pmr";

const orderEntered : PMR.OrderEntered = {
    messageType: PMR.MessageType.ORDER_ENTERED ,
    timestamp: 123456,
    username: "username",
    orderNumber: 123456,
    side: PMR.Side.BUY,
    instrument: "ETH-BTC",
    quantity: 2,
    price: 30,
};

const formattedMessage: Buffer = PMR.format(orderEntered);

const parsedMessage = PMR.parse(formattedMessage);

const oe: PMR.OrderEntered = <PMR.OrderEntered>parsedMessage;
```

I was unable to run tests.

### CODE REVIEW

**Comment by jvirtanen** [comment]
Thanks for this, @leovujanic! 👍 I'll have a look soon.

**Comment by jvirtanen** [comment]
Hi @leovujanic, my apologies for the delay. In general, looking good! 🙌

Some small nits:
- Could you maintain the existing 2-space indentation?
- Could you keep using single quote (`'`) rather than double quote (`"`) for strings?

**Comment by leovujanic** [comment]
Hi @jvirtanen , sorry for late response. I finally managed to fix my mess with indents. Also, I have changed the quotes. If you are OK with this changes I would like to update PR-s for POE and PMD analogically.

**Comment by jvirtanen** [comment]
Thank you @leovujanic, merging! 👍  Yes, similar changes for POE and PMD would be most welcome. 🙂

**Comment by leovujanic** [comment]
Thank you @jvirtanen , it's a pleasure to work with you. :) I will make changes for POE and PMD during the weekend.

**Comment by jvirtanen** [comment]
Likewise, @leovujanic. Keep up the good work! 🙌

**Pull request merged**
